language: php

php:
  - '5.6'
  - '7.0'
  - nightly

install:
  - composer install

script: 
  - mkdir -p build/logs
  - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls