language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer install

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --ignore=vendor --standard=coding_standard.xml .
  - vendor/bin/phpstan analyze --level max src/

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi